# .github/workflows/ping.yml
name: Keep Render App Awake

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:       # Permite correrlo manualmente tambi√©n

jobs:
  ping-render:
    runs-on: ubuntu-22.04
    steps:
      - name: Ping Render App
        run: curl -s https://mainomai.onrender.com
